version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: bcb-postgres
    environment:
      POSTGRES_DB:       ${POSTGRES_DB}
      POSTGRES_USER:     ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bcb-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bcb-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER:     admin
      RABBITMQ_DEFAULT_PASS:     admin123
      RABBITMQ_DEFAULT_VHOST:    /
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/rabbitmq.conf:ro
    networks:
      - bcb-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bcb-api
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:        jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME:   ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD:   ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST:         rabbitmq
      SPRING_RABBITMQ_PORT:         5672
      SPRING_RABBITMQ_USERNAME:     admin
      SPRING_RABBITMQ_PASSWORD:     admin123
      SPRING_RABBITMQ_VIRTUAL_HOST: /
      JWT_SECRET:                   ${JWT_SECRET}
    env_file:
      - .env
    networks:
      - bcb-network

volumes:
  postgres-data:

networks:
  bcb-network:
