version: '3.9'

services:
  postgres:
    image: postgres
    container_name: bcb-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bcb-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bcb-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bcb-network

  api:
    build: .
    container_name: bcb-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - bcb-network
    env_file:
      - .env

volumes:
  postgres-data:

networks:
  bcb-network:
